branches:
  except:
  - experimental

language: bash

services:
  - docker

stages:
  - DockerBuild
  - name: DockerPush
    if: branch = master and NOT type = pull_request

jobs:
  include:
    - stage: DockerBuild
      script: 
        - docker build . -t theapp:latest
        - docker run --rm -d -p 8001:8001 -t theapp:latest
        - docker ps -a
    - stage: DockerPush
      script: 
        - make dockerbuild dockerpush tag        