branches:
  except:
  - experimental

language: bash

services:
  - docker

before_install:
- docker build . -t theapp:latest
- docker run --rm -d -p 8001:8001 -t theapp:latest
- docker ps -a

script:
- if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
  make dockerpush; fi
